site_name: LumosImago
theme:
  name: material
  features:
    - navigation.tabs
    - toc.integrate
  language: fr

copyright: |
  &copy; 2024 <a href="https://github.com/drlefevre" target="_blank" rel="noopener">Alexandre Lefèvre</a>
