site_name: LumosImago

nav:
  - index.md
  - Anatomie: anat.md
  - Thorax: 
    - Détresse respiratoire: thorax/détresse.md
    - Douleurs aiguës: thorax/douleurs.md
    - Infections: thorax/infections.md
    - PID: thorax/PID.md
    - Tumeurs: thorax/tumeurs.md
  - Abdomen et pelvis: 
    - Syndrome occlusif: abdo/occlusion.md
    - Douleurs abdominales: abdo/douleurs.md
    - Douleurs uro-gynéco: abdo/uro-gynéco.md
    - Tumeurs digestives: abdo/tumdig.md
    - Tumeurs uro-gynéco: abdo/tumurogyn.md
  - Neurologie et ORL: 
    - Urgences: neuro/urgences.md
    - Traumatisme: neuro/TC.md
    - Confusion/démences: neuro/démences.md
    - ORL et ophtalmologie: neuro/ORL.md
    - Tumeurs: neuro/tumeurs.md
  - Ostéo et hémato: 
    - Traumatique: ostéo/fractures.md
    - Arthrose/arthrite: ostéo/arthrose.md
    - Hémopathies: ostéo/hémopathies.md
  - Pédiatrie: 
    - Urgences du nourrisson: pédia/urgnourrisson.md
    - Urgences de l'enfant: pédia/urgenfant.md
    - Fractures et boiterie: pédia/fractures.md
    - Cancers: pédia/cancers.md
    - Maladies génétiques: pédia/génétique.md
  - Quiz: quiz/funnymonday.md

theme:
  name: material
  language: fr
  palette:
    primary: indigo
    accent: indigo
  favicon: assets/logo maj.svg
  logo: assets/logo maj.svg
  custom_dir: overrides/

plugins:
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.caret
  - toc:
      toc_depth: 3
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons/

copyright: |
  &copy; 2024 Alexandre Lefèvre - lumosimago@gmail.com

extra:
  generator: false

extra_css:
  - stylesheets/extra.css
