site_name: LumosImago

nav:
  - index.md
  - Anatomie:
    - Tête et cou: anat/tête-cou.md
    - Thorax: anat/thorax.md
    - Abdomen et pelvis: anat/abdo-pelv.md
    - Membres: anat/membres.md
  - Tumeurs: 
    - Intracrâniennes: tumeurs/intracrâniennes.md
    - Pulmonaires et ORL: tumeurs/pulmonaires.md
    - Digestives: tumeurs/digestives.md
    - Uro-gynécologiques: tumeurs/uro-gynécologiques.md
    - Hémopathies: tumeurs/hémopathies.md
  - Thorax: 
    - Détresse respiratoire: thorax/détresse.md
    - Douleurs aiguës: thorax/douleurs.md
    - Infections: thorax/infections.md
    - PID: thorax/PID.md
  - Abdomen et pelvis: 
    - Douleurs quadrants sup.: abdo-pelv/douleurssup.md
    - Douleurs quadrants inf.: abdo-pelv/douleursinf.md
    - Douleurs lombaires: abdo-pelv/douleurslombaires.md
    - Syndrome occlusif: abdo-pelv/occlusion.md
    - AVP: abdo-pelv/AVP.md
  - Neurologie et ORL: 
    - Urgences: neuro/urgences.md
    - Traumatisme: neuro/TC.md
    - Confusion/démences: neuro/démences.md
    - ORL et ophtalmologie: neuro/ORL.md
  - Ostéo-articulaire: 
    - Fractures pathologiques: ostéo/fracturespatho.md
    - Ostéoporose: ostéo/ostéoporose.md
    - Arthrose: ostéo/arthrose.md
    - Arthrite: ostéo/arthrite.md
  - Pédiatrie: 
    - Urgences du nourrisson: pédia/urgnourrisson.md
    - Urgences de l'enfant: pédia/urgenfant.md
    - Fractures et boiterie: pédia/fractures.md
    - Cancers: pédia/cancers.md
    - Maladies génétiques: pédia/génétique.md
  - Quiz:
    - Funny Monday: quiz/funnymonday.md

theme:
  name: material
  language: fr
  palette:
    primary: indigo
    accent: indigo
  favicon: assets/logo maj.svg
  logo: assets/logo maj.svg
  custom_dir: overrides/

plugins:
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.caret
  - toc:
      toc_depth: 3
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons/

copyright: |
  &copy; 2024 Alexandre Lefèvre - lumosimago@gmail.com

extra:
  generator: false

extra_css:
  - stylesheets/extra.css
