site_name: LumosImago
theme:
  name: material
  features:
    - navigation.tabs
  language: fr
  palette:
    primary: indigo
    accent: deep purple
  favicon: assets/logo brain.svg
  logo: assets/logo brain.svg

markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      toc_depth: 3

copyright: |
  &copy; 2024 <a href="https://github.com/drlefevre" target="_blank" rel="noopener">Alexandre Lefèvre</a>
