site_name: LumosImago

nav:
  - index.md
  - Anatomie:
    - Tête et cou: anat/tête-cou.md
    - Thorax: anat/thorax.md
    - Abdomen et pelvis: anat/abdo-pelv.md
    - Membres: anat/membres.md
  - Tumeurs: 
    - Intracrâniennes: tumeurs/intracrâniennes.md
    - Pulmonaires: tumeurs/pulmonaires.md
    - Hépatiques: tumeurs/hépatiques.md
    - Digestives: tumeurs/digestives.md
    - Urologiques: tumeurs/urologiques.md
    - Gynécologiques: tumeurs/gynécologiques.md
    - Hémopathies: tumeurs/hémopathies.md
  - Thorax: 
    - EP: thorax/EP.md
    - PID: thorax/PID.md
    - Infections: thorax/infections.md
    - Hémoptysie: thorax/hémoptysies.md
    - Pneumothorax: thorax/pneumothorax.md
  - Abdo-pelv: 
    - Douleurs quadrants supérieurs: abdo-pelv/douleurs sup.md
    - Douleurs quadrants inférieurs: abdo-pelv/douleurs inf.md
    - Douleurs lombaires: abdo-pelv/douleurs lombaires.md
    - Syndrome occlusif: abdo-pelv/sd occlusif.md
    - AVP: abdo-pelv/AVP.md
  - Ostéo-articulaire: 
    - Fractures pathologiques: ostéo/fractures patho.md
    - Ostéoporose: ostéo/ostéoporose.md
    - Arthrose: ostéo/arthrose.md
    - Arthrite: ostéo/arthrite.md
  - Neurologie: 
    - AVC: neuro/AVC.md
    - TC: neuro/TC.md
    - SEP: neuro/SEP.md
    - Démences: neuro/démences.md
    - Sciatique: neuro/sciatique.md
    - Alcool: neuro/alcool.md
  - ORL/CMF:
    - Fractures: ORL-CMF/fractures.md
    - Schwannome vestibulaire: ORL-CMF/schwannome.md
    - Parotides: ORL-CMF/parotides.md
    - Denture: ORL-CMF/denture.md
  - Pédiatrie: 
    - Fractures: pédia/fractures.md
    - Maltraitance: pédia/maltraitance.md
    - Tumeurs: pédia/tumeurs.md
    - Boiterie: pédia/boiterie.md

theme:
  name: material
  language: fr
  palette:
    primary: indigo
    accent: indigo
  favicon: assets/logo maj.svg
  logo: assets/logo maj.svg

plugins:
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.caret
  - toc:
      toc_depth: 3
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 Alexandre Lefèvre

extra:
  generator: false

extra_css:
  - stylesheets/extra.css
